image: openjdk:8

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew clean build
  artifacts:
    paths:
      - referally-console/build/dist
      - referally-integration/build/dist
      - referally-service/build/libs/referally-service.war

deploy:
  stage: deploy
  script:
    - chmod +x cicd/deploy.sh
    - ./cicd/deploy.sh
  dependencies:
    - build
