image: openjdk:8

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew clean build

deploy:
  stage: deploy
  script:
    - chmod +x cicd/deploy.sh
    - ./deploy.sh
  dependencies:
    - build
