# Empty values request
POST http://localhost:8080/registration
Content-Type: application/json

{
  "name": "",
  "email": "",
  "password": "",
  "r_password": ""
}

###

# Invalid values request
POST http://localhost:8080/registration
Content-Type: application/json

{
  "name": "qqqq12",
  "email": "wwwww",
  "password": "eeee",
  "r_password": "eeee"
}

###

# Valid values, passwords not equivalence, email not unique request
POST http://localhost:8080/registration
Content-Type: application/json

{
  "name": "ivan",
  "email": "ivan@qwe.qwe",
  "password": "Eeeee123",
  "r_password": "Qqqqq123"
}

###

# Empty values request
POST http://localhost:8080/registration
Content-Type: application/json

{
  "name": "newname",
  "email": "newemail@email.em",
  "password": "Eeeee123",
  "r_password": "Eeeee123"
}
